 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  ok_vqa_instruct:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]
    instruction_path: './lavis/datasets/datasets/instructions/vqa_instructions.txt'

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
              # TODO make this order insensitive
              - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/okvqa/okvqa_train.json
              # - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/okvqa/OpenEnded_mscoco_train2014_questions.json
              # - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/okvqa/mscoco_train2014_annotations.json
          storage:
              - okvqa/annotations/okvqa_train.json
              # - okvqa/annotations/OpenEnded_mscoco_train2014_questions.json
              # - okvqa/annotations/mscoco_train2014_annotations.json
        test:
          url:
              # TODO make this order insensitive
              - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/okvqa/okvqa_val_eval.json
              - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/okvqa/okvqa_answer_list_train.json
              - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/okvqa/OpenEnded_mscoco_val2014_questions.json
              - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/okvqa/mscoco_val2014_annotations.json
          storage:
              - okvqa/annotations/vqa_val_eval.json
              - okvqa/annotations/answer_list.json
              - okvqa/annotations/OpenEnded_mscoco_val2014_questions.json
              - okvqa/annotations/mscoco_val2014_annotations.json
      images:
          storage: coco/images/
